// Sync shared/datasets/benchmarks.jsonl into a bundled TypeScript catalog module so
// the DeskAgent model picker has an offline fallback (Phase 6 Task 2).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const dataset = path.join(root, "shared", "datasets", "benchmarks.jsonl");
const outDir = path.join(root, "apps", "deskagent", "src", "lib");
const outFile = path.join(outDir, "benchkit-catalog.ts");

const lines = readFileSync(dataset, "utf8")
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean)
  .map((l) => JSON.parse(l));

mkdirSync(outDir, { recursive: true });
const body = lines
  .map((row) => {
    const picked = {
      model: row.model,
      hardware: {
        cpu: row.hardware?.cpu ?? "unknown",
        ram_gb: row.hardware?.ram_gb ?? 0,
        gpu: row.hardware?.gpu ?? null,
        os: row.hardware?.os ?? null,
      },
      runtime: row.runtime,
      quantization: row.quantization ?? null,
      tokens_per_sec: row.tokens_per_sec ?? null,
      peak_ram_gb: row.peak_ram_gb ?? null,
      source_url: row.source_url,
    };
    return `  ${JSON.stringify(picked)},`;
  })
  .join("\n");

const module = `// AUTO-GENERATED by scripts/sync-catalog.mjs — DO NOT EDIT.
// Offline fallback catalog for the DeskAgent model picker (Phase 6 Task 2).
// Mirrors shared/datasets/benchmarks.jsonl; regenerate with:
//   node apps/deskagent/scripts/sync-catalog.mjs
export interface BenchRow {
  model: string;
  hardware: { cpu: string; ram_gb: number; gpu?: string | null; os?: string | null };
  runtime: string;
  quantization?: string | null;
  tokens_per_sec?: number | null;
  peak_ram_gb?: number | null;
  source_url: string;
}

export const BENCHKIT_CATALOG: BenchRow[] = [
${body}
];

export const CATALOG_SOURCE = "shared/datasets/benchmarks.jsonl (DEC-0006)";
`;

writeFileSync(outFile, module);
console.log(`wrote ${outFile} (${lines.length} rows)`);
